# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: left_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - tracebot_left_arm_shoulder_pan_joint
    - tracebot_left_arm_shoulder_lift_joint
    - tracebot_left_arm_elbow_joint
    - tracebot_left_arm_wrist_1_joint
    - tracebot_left_arm_wrist_2_joint
    - tracebot_left_arm_wrist_3_joint
    - tracebot_right_arm_shoulder_pan_joint
    - tracebot_right_arm_shoulder_lift_joint
    - tracebot_right_arm_elbow_joint
    - tracebot_right_arm_wrist_1_joint
    - tracebot_right_arm_wrist_2_joint
    - tracebot_right_arm_wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 500
controller_list:
  - name: left_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - tracebot_left_arm_shoulder_pan_joint
      - tracebot_left_arm_shoulder_lift_joint
      - tracebot_left_arm_elbow_joint
      - tracebot_left_arm_wrist_1_joint
      - tracebot_left_arm_wrist_2_joint
      - tracebot_left_arm_wrist_3_joint
  - name: right_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - tracebot_right_arm_shoulder_pan_joint
      - tracebot_right_arm_shoulder_lift_joint
      - tracebot_right_arm_elbow_joint
      - tracebot_right_arm_wrist_1_joint
      - tracebot_right_arm_wrist_2_joint
      - tracebot_right_arm_wrist_3_joint
right_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - tracebot_right_arm_shoulder_pan_joint
    - tracebot_right_arm_shoulder_lift_joint
    - tracebot_right_arm_elbow_joint
    - tracebot_right_arm_wrist_1_joint
    - tracebot_right_arm_wrist_2_joint
    - tracebot_right_arm_wrist_3_joint
  gains:
    tracebot_right_arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_right_arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_right_arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_right_arm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_right_arm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_right_arm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    tracebot_left_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10
  
left_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - tracebot_left_arm_shoulder_pan_joint
    - tracebot_left_arm_shoulder_lift_joint
    - tracebot_left_arm_elbow_joint
    - tracebot_left_arm_wrist_1_joint
    - tracebot_left_arm_wrist_2_joint
    - tracebot_left_arm_wrist_3_joint
  gains:
    tracebot_left_arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_left_arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_left_arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_left_arm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_left_arm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tracebot_left_arm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    tracebot_left_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    tracebot_left_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10
