combined_hardware_interface:
  robot_hardware:
    - left_ur_hw
    - right_ur_hw

  left_ur_hw:
    type: ros_control_boilerplate/SimHWInterface
    joints: &left_robot_joints
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    hardware_interface:
      joints: *left_robot_joints
      sim_control_mode: 1      # 0: position, 1: velocity

  right_ur_hw:
    type: ros_control_boilerplate/SimHWInterface
    joints: &right_robot_joints
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    hardware_interface:
      joints: *right_robot_joints
      sim_control_mode: 1      # 0: position, 1: velocity

generic_hw_control_loop:
  loop_hz: 500
  cycle_time_error_threshold: 0.002
