<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="tracebot_mockup" params="robot_name
                                              mount_base_width
                                              mount_base_length
                                              mount_base_height
                                              arm_mount_offset_x:=0
                                              arm_mount_offset_y:=0
                                              arm_mount_offset_z:=0
                                              arm_mount_offset_theta:=0
                                              arm_base_tilt:=0
                                              left_arm_model
                                              right_arm_model
                                              camera_mount_offset_z">
    <!-- Base -->
    <link name="${robot_name}_base_link"/>
    
    <joint name="${robot_name}_mount_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${robot_name}_base_link"/>
      <child link="${robot_name}_arm_mount_base"/>
    </joint>

    <link name="${robot_name}_arm_mount_base">
      <visual>
        <origin xyz="0 0 ${mount_base_height/2}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://tracebot_mockup_description/meshes/stand.stl" />
        </geometry>
        <material name="grey">
          <color rgba="0.6 0.6 0.6 1.0"/>
        </material>
      </visual>
    </link>
    
    <!-- Arm Setup -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>
    <!-- Left Arm Mount -->
    <joint name="${robot_name}_left_arm_mount_joint" type="fixed">
      <origin xyz="${-arm_mount_offset_x} 0 ${mount_base_height-arm_mount_offset_z}" rpy="0 ${-pi/2+arm_base_tilt} 0"/>
      <parent link="${robot_name}_arm_mount_base"/>
      <child link="${robot_name}_left_arm_mount"/>
    </joint>
    
    <link name="${robot_name}_left_arm_mount"/>
    
    <joint name="${robot_name}_left_arm_base_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 1.5708"/>
      <parent link="${robot_name}_left_arm_mount"/>
      <child link="${robot_name}_left_arm_base_link"/>
    </joint>
  
    <xacro:ur_robot prefix="${robot_name}_left_arm_"
      joint_limits_parameters_file="$(find ur_description)/config/$(arg left_arm_model)/joint_limits.yaml"
      kinematics_parameters_file="$(find ur_description)/config/$(arg left_arm_model)/default_kinematics.yaml"
      physical_parameters_file="$(find ur_description)/config/$(arg left_arm_model)/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description)/config/$(arg left_arm_model)/visual_parameters.yaml"
      transmission_hw_interface="hardware_interface/PositionJointInterface"
      safety_limits="false"
      safety_pos_margin="0.15"
      safety_k_position="20"/>
    
    
    <!-- Right Arm Mount -->
    <joint name="${robot_name}_right_arm_mount_joint" type="fixed">
      <origin xyz="${arm_mount_offset_x} 0 ${mount_base_height-arm_mount_offset_z}" rpy="0 ${pi/2-arm_base_tilt} 0"/>
      <parent link="${robot_name}_arm_mount_base"/>
      <child link="${robot_name}_right_arm_mount"/>
    </joint>
    
    <link name="${robot_name}_right_arm_mount"/>
    
    <joint name="${robot_name}_right_arm_base_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 -1.5708"/>
      <parent link="${robot_name}_right_arm_mount"/>
      <child link="${robot_name}_right_arm_base_link"/>
    </joint>
  
    <xacro:ur_robot prefix="${robot_name}_right_arm_"
      joint_limits_parameters_file="$(find ur_description)/config/$(arg right_arm_model)/joint_limits.yaml"
      kinematics_parameters_file="$(find ur_description)/config/$(arg right_arm_model)/default_kinematics.yaml"
      physical_parameters_file="$(find ur_description)/config/$(arg right_arm_model)/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description)/config/$(arg right_arm_model)/visual_parameters.yaml"
      transmission_hw_interface="hardware_interface/PositionJointInterface"
      safety_limits="false"
      safety_pos_margin="0.15"
      safety_k_position="20"/>
    
    <!-- Camera Mount -->
    <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
    
    <joint name="${robot_name}_camera_mount_joint" type="fixed">
      <origin xyz="0 0 ${mount_base_height+camera_mount_offset_z}" rpy="0 0 0"/>
      <parent link="${robot_name}_arm_mount_base"/>
      <child link="${robot_name}_camera_mount"/>
    </joint>
    
    <link name="${robot_name}_camera_mount"/>
    
    <xacro:sensor_d435 parent="${robot_name}_camera_mount" 
      use_nominal_extrinsics="false" 
      add_plug="false" 
      use_mesh="true"
      name="${robot_name}_camera">
      <origin xyz="0 0 0" rpy="0 0.785398 1.5708"/>
    </xacro:sensor_d435>
  </xacro:macro>
</robot>
