<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="tracebot_mockup" 
    params="
    robot_mount_offset_x
    robot_mount_offset_y
    robot_mount_offset_z
    robot_mount_offset_theta
    robot_mount_height
    robot_mount_length
    robot_mount_width
    robot_base_tilt
    left_arm
    right_arm">

    <link name="robot_base_link"/>
    
    <joint name="robot_mount_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="robot_base_link"/>
      <child link="robot_mount_base"/>
    </joint>

    <link name="robot_mount_base">
      <visual>
        <origin xyz="0 0 ${robot_mount_height/2}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file:///home/benrjg/astech_wss/tracebot_mockup_ws/src/tracebot_mockup/tracebot_mockup_description/meshes/stand.stl" />
        </geometry>
        <material name="grey">
          <color rgba="0.6 0.6 0.6 1.0"/>
        </material>
      </visual>
    </link>

    <!-- Left Arm Mount -->
    <joint name="left_robot_mount_joint" type="fixed">
      <origin xyz="${-robot_mount_offset_x} 0 ${robot_mount_height-robot_mount_offset_z}" rpy="0 ${-pi/2+robot_base_tilt} 0"/>
      <parent link="robot_mount_base"/>
      <child link="left_robot_mount"/>
    </joint>
    
    <link name="left_robot_mount"/>
    
    <!-- Right Arm Mount -->
    <joint name="right_robot_mount_joint" type="fixed">
      <origin xyz="${robot_mount_offset_x} 0 ${robot_mount_height-robot_mount_offset_z}" rpy="0 ${pi/2-robot_base_tilt} 0"/>
      <parent link="robot_mount_base"/>
      <child link="right_robot_mount"/>
    </joint>
    
    <link name="right_robot_mount"/>



  </xacro:macro>

</robot>
